apiVersion: v2
name: elastic-search
type: application
description: Installs Elastic Search Instances
version: 0.0.1
appVersion: 8.17.0
maintainers:
  - name: danielscholl
    url: https://github.com/danielscholl